### ISSUE TITLE
zip plugin error en opencart 4.0.1.1

### ISSUE THREAD

**Issue by Andresfze** [TransbankDevelopers/transbank-plugin-opencart-webpay-rest#23]
al intentar instalar el ultimo plugin de transbank 1.1.2 para opencart, dentro de la instalacion de modulos de opencart 4.0.1.1 no instala el zip, ya que indica que falta un archivo y no permite continuar, intente de realizarlo de forma manual copiando y pegando manual las librerias en modulos y tampoco funciona

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 1.1.2
- Opencart: 4.0.1.1
- PHP: 8.0+

**Comment by otrab** [comment]
Hola [Andresfze](https://github.com/Andresfze)
Actualmente solo damos soporte hasta la versión 3.x de opencart

Prueba instalando opencart 3.0.3.8 
https://www.opencart.com/index.php?route=cms/download/download&download_id=64


Saludos!

**Comment by Andresfze** [comment]
favor actualizar el soporte a la version 4.x, Opercart 3.x esta desactualizado u obsoleto

Gracias
