### ISSUE TITLE
Probando plugin en OpenCart Version 4.0.2.3

### ISSUE THREAD

**Issue by srgio1** [TransbankDevelopers/transbank-plugin-opencart-webpay-rest#44]
Hola, estoy probando OpenCart (Versión 4.0.2.3) y no pude instalar el plugin. Me salió un error diciendo que faltaba el archivo install.json . ¿Estaré haciendo algo mal o el plugin no funciona con esta versión de OpenCart?
Gracias, saludos.

**Comment by mastudillot** [comment]
Hola

No se ha probado el plugin en la nueva versión de OpenCart, hasta ahora solo damos soporte a la versión 3.x de OpenCart.

Por ahora veo complejo que podamos hacer una actualización para dar soporte a esa versión, ya que entre la versión 3 y 4 cambia un poco la estructura del módulo.
