### ISSUE TITLE
Error al pasar a "produccion"

### ISSUE THREAD

**Issue by lpintod1986** [TransbankDevelopers/transbank-plugin-opencart-webpay-rest#7]
**Describe el bug**

Al intentar pasar a producción las api key entregadas por transbank este arroja error de "INDEX PRODUCCION"

Para reproducir

1. Agregar productos al carro e intentar realizar el pago

**Comportamiento observado**

No permite llegar a la pantalla de transbank para realizar el pago.

**Comportamiento esperado**

Debería pasar a la pantalla de transbank con la linea indicada en mi foto (código PHP).

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/50028959/105806112-21a85800-5f82-11eb-9798-a4eccf90343e.png)
![image](https://user-images.githubusercontent.com/50028959/105806149-35ec5500-5f82-11eb-8311-eb94580b9fc2.png)

Versiones :
- Plugin: [1.0.0]
- Opencart: [3.0.3.6]
- PHP: [7.1.33]

**Contexto adicional**

Si bien luego de realizar un pago este sigue arrojando error en el retorno.
Que seria el que adjunto a continuación para el cual desconozco como solucionar.

![image](https://user-images.githubusercontent.com/50028959/105806864-86b07d80-5f83-11eb-8d3c-7884a190c366.png)

**Comment by isabellaahc** [comment]
Gracias por reportar @lpintod1986. Revisaremos para responder en breve.

**Comment by lpintod1986** [comment]
@isabellaahc el segundo error que indico como "Contexto adicional" se soluciona agregando lo siguiente en la configuración de Apache2.

Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure;SameSite=None

y el primer error se soluciona con lo indicado mas arriba agregando "PRODUCCION" => "https://webpay3g.transbank.cl/"  al archivo WebpayPlus.php

Con eso queda OK el plugin.

**Comment by isabellaahc** [comment]
Hola @lpintod1986. 
Te cuento que se encuentra disponible una nueva versión del plugin de Opencart que resuelve este error.
Lo puedes encontrar [aquí](https://github.com/TransbankDevelopers/transbank-plugin-opencart-webpay-rest).

Recuerda que ante cualquier duda nos puedes contactar por [slack](https://join.slack.com/t/transbankdevelopers/shared_invite/zt-lcnd28x3-UK0u~C~AyRxJloJQtaFHBQ).
